name: Configure HTTPS in EC2

on:
  workflow_call:
    inputs:
      dockerExposedPort:
        required: true
        type: number
      httpsConfigFilePath:
        required: false
        default: ./tmp/aws-ec2-configure-https-resources/https_custom.conf
        type: string
    secrets:
      AWS_DEPLOY_ACCESS_KEY_ID:
        required: true
      AWS_DEPLOY_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_EC2_INSTANCE_ID:
        required: true
      SSH_KEY:
        required: true
      SSH_USER:
        required: true
      DOMAIN_RECORD_NAME:
        required: true
      EMAIL:
        required: true
jobs:
  configure-nginx-and-letsencrypt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions repository # Clone this repository in tmp folder to get access to resources
        uses: actions/checkout@v3
        with:
          repository: lemoncode/actions
          ref: main
          path: tmp
      - name: AWS login
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Set EC2 Public IP environment variable
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID}} --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
      - name: Configure Nginx and Let's encrypt
        run: |
          echo "${{secrets.SSH_KEY}}" > private-key
          sudo chmod 600 private-key
          scp -o StrictHostKeyChecking=no -i private-key -r ./tmp ${{secrets.SSH_USER}}@$PUBLIC_IP:~/nginx-config
          ls -la

